<style>
#wms-chat-toggle{position:fixed;right:24px;bottom:22px;z-index:1060;border:0;border-radius:28px;background:#344767;color:white;padding:14px 22px;box-shadow:0 6px 20px #0003;font-weight:600}
#wms-chat{position:fixed;right:24px;bottom:86px;width:min(560px,calc(100vw - 32px));height:min(640px,calc(100dvh - 110px));z-index:1060;background:#fff;border:1px solid #e2e8f0;border-radius:18px;box-shadow:0 12px 40px #0003;overflow:hidden;display:flex;flex-direction:column;color:#344767;font-size:14px}
#wms-chat[hidden]{display:none}#wms-chat header{padding:16px;background:#344767;color:#fff;display:flex;align-items:center;justify-content:space-between;gap:8px}#wms-chat header button{background:transparent;color:#fff;border:1px solid #ffffff60;border-radius:8px;padding:5px 9px}#wms-chat-log{flex:1;overflow:auto;padding:16px;min-height:0}.wms-chat-message{padding:12px;border-radius:12px;background:#f1f5f9;margin-bottom:12px;white-space:pre-wrap;overflow-wrap:anywhere}.wms-chat-message.user{background:#e8eaff;margin-left:38px}.wms-chat-table{overflow-x:auto;margin-top:10px}.wms-chat-table table{font-size:12px;border-collapse:collapse;width:100%;white-space:nowrap}.wms-chat-table th,.wms-chat-table td{padding:7px;border-bottom:1px solid #dce3ec;text-align:left}.wms-chat-message small{display:block;margin-top:8px;color:#64748b}#wms-chat-suggestions{padding:8px 12px;display:flex;gap:6px;overflow-x:auto}#wms-chat-suggestions button{white-space:nowrap;border:1px solid #dce3ec;background:#fff;border-radius:16px;padding:5px 10px;color:#344767;font-size:12px}#wms-chat-form{display:flex;gap:8px;padding:12px;border-top:1px solid #e2e8f0}#wms-chat-input{flex:1;min-width:0;border:1px solid #cbd5e1;border-radius:10px;padding:10px}#wms-chat-send{background:#344767;color:white;border:0;border-radius:10px;padding:10px}#wms-chat button:disabled{opacity:.5}#wms-chat-status{padding:0 16px;font-size:12px;color:#64748b}@media(max-width:576px){#wms-chat{right:16px}#wms-chat-toggle{right:16px}}
</style>
<button id="wms-chat-toggle" type="button" aria-controls="wms-chat" aria-expanded="false">Chat Asisten WMS</button>
<section id="wms-chat" hidden role="region" aria-label="Asisten WMS" data-endpoint="{{ route('chatbot.message') }}" data-csrf="{{ csrf_token() }}">
    <header><div><strong>Asisten WMS</strong><br><small id="wms-chat-mode">{{ config('chatbot.provider') === 'gemini' && config('chatbot.api_key') ? 'AI Gemini - data dari database' : 'AI belum aktif - pencarian dasar' }}</small></div><div><button type="button" id="wms-chat-clear">Chat baru</button> <button type="button" id="wms-chat-close" aria-label="Tutup chatbot">&#215;</button></div></header>
    <div id="wms-chat-log" role="log" aria-live="polite" aria-relevant="additions"></div>
    <div id="wms-chat-status" role="status"></div>
    <div id="wms-chat-suggestions" aria-label="Contoh pertanyaan"></div>
    <form id="wms-chat-form"><label for="wms-chat-input" class="visually-hidden">Pertanyaan</label><input id="wms-chat-input" type="text" maxlength="500" required autocomplete="off" placeholder="Contoh: stok barang ABC berapa?"><button type="submit" id="wms-chat-send">Kirim</button></form>
</section>
<script src="{{ asset('assets/js/wms-chatbot.js') }}" defer></script>
